"""
Python module with utility functions of various types
"""

import json
import os
import pickle
import time
from collections import namedtuple
from typing import List, Optional, Type, Union

import ipdb
import numpy as np
import numpy.typing as npt
import pandas as pd
from sklearn.ensemble import IsolationForest
from utils_reboot.datasets import Dataset

Precisions = namedtuple(
    "Precisions", ["direct", "inverse", "dataset", "model", "value"]
)
NewPrecisions = namedtuple(
    "NewPrecisions", ["direct", "inverse", "dataset", "model_name", "value", "aucfs"]
)
Precisions_random = namedtuple("Precisions_random", ["random", "dataset", "model_name"])


def update_feature_names(
    dataset_name: str,
    feature_names_filepath: Optional[str] = "../datasets/data/data_feature_names.json",
    feature_names: Optional[list[str]] = None,
) -> None:
    """
    Function to update the feature names of a new dataset in the `data_feature_names.json` file.

    Args:
        dataset: Input dataset
        dataset_name: Dataset name
        feature_names_filepath: Path to the json file to update
        feature_names: List of string containing the feature names

    Returns:
        The function updates the feature names json file and does not return any value
    """

    with open(feature_names_filepath) as f:
        data_feature_names = json.load(f)

    data_feature_names[dataset_name] = feature_names

    with open(feature_names_filepath, "w") as f:
        json.dump(data_feature_names, f)


def get_feature_indexes(
    dataset: Dataset,
    f1: Union[str, int],
    f2: Union[str, int],
) -> tuple[int, int]:
    """
    Function to get the indexes of two features in the dataset.

    Args:
        dataset: Dataset
        f1: Name of the first feature
        f2: Name of the second feature

    Returns:
        Indexes of the two features in the dataset
    """

    feature_names = dataset.feature_names

    if (isinstance(f1, int)) and (isinstance(f2, int)):
        return f1, f2
    else:
        try:
            idx1 = feature_names.index(f1)
        except ValueError:
            raise ValueError("Feature name not valid")
        try:
            idx2 = feature_names.index(f2)
        except ValueError:
            raise ValueError("Feature name not valid")

    return idx1, idx2


def get_current_time() -> str:
    """
    This function returns the current time in the format 'dd-mm-YYYY_HH-MM-SS'.
    It is used to produce the name of the files saved

    Returns:
        current_time: string representing the current time

    """

    t = time.localtime()
    current_time = time.strftime("%d-%m-%Y_%H-%M-%S", t)
    return current_time


def save_element(
    element: Union[
        dict,
        np.ndarray,
        list,
        pd.DataFrame,
        Precisions,
        NewPrecisions,
        Precisions_random,
    ],
    directory_path: str,
    filename: str = "",
    filetype: str = "pickle",
    add_time: bool = True,
) -> None:
    """
    Function to save an element produced by an experiment in a file (i.e. `npz` or `pickle` file) in the specified directory path.

    Args:
        element: Element to be saved
        directory_path: Directory path where the file will be saved
        filename: Name of the file
        filetype: Type of the file (i.e. `npz` or `pickle`)
        add_time: boolean flag to see weather to add the current time to the filename

    Returns:
        The method saves element and does not return any value
    """

    filetypes = ["pickle", "npz", "csv.gz", "json"]

    assert filetype in filetypes, f"filetype must be one of {filetypes}"

    if add_time:
        current_time = get_current_time()
        filename = current_time + "_" + filename

    path = directory_path + "/" + filename

    if filetype == "pickle":
        with open(path + ".pickle", "wb") as fl:
            pickle.dump(element, fl)
    elif filetype == "npz":
        np.savez(path, element=element)
    elif filetype == "csv.gz":
        if isinstance(element, np.ndarray):
            # Convert numpy array to pandas DataFrame
            element = pd.DataFrame(element)
        element.to_csv(path + ".csv.gz", index=False, compression="gzip")
    elif filetype == "json":
        with open(path, "w") as fl:
            json.dump(element, fl, indent=4)


def generate_path(basepath: str = os.getcwd(), folders: List[str] = []) -> str:
    """
    Generate a path starting from a basepath and a list of folders to join to the basepath.

    Args:
        basepath: The basepath from which to start to generate the path, by default os.getcwd()
        folders: A list of strings containing the ordered list of subfolders to join to the basepath, by default []
    Returns:
        path: The path generated by joining the basepath and the folders
    """

    # Verify weather basepath is a valid path in the system
    assert os.path.exists(basepath), f"Basepath {basepath} does not exist"

    path = basepath + "/"

    # Join the basepath with the folders
    for folder in folders:
        path = os.path.join(path, folder) + "/"
        # Verify weather the path exists or not
        if not os.path.exists(path):
            os.makedirs(path)

    return path[:-1]


def get_most_recent_file(directory_path: str, file_pos: int = 0) -> str:
    """
    Function to get the most recent file (i.e. last modified file) in a directory path.

    Args:
        directory_path: Directory path where the files are stored
        file_pos (int): position of the file to retrieve, by default is 0 (most recent file), file_pos=1 will retrieve the second most recent file and so on

    Returns:
        Path to the most recent file in the directory path

    """

    # NOTE: Insert here only the files contained in directory_path, do
    # not consider subdirectories
    files_list = [
        x
        for x in os.listdir(directory_path)
        if os.path.isfile(os.path.join(directory_path, x))
    ]

    files = sorted(
        files_list,
        key=lambda x: os.path.getmtime(os.path.join(directory_path, x)),
        reverse=True,
    )

    return os.path.join(directory_path, files[file_pos])


def open_element(
    file_path: str, filetype: str = "pickle"
) -> Union[
    np.ndarray,
    list,
    pd.DataFrame,
    Type[Precisions],
    Type[NewPrecisions],
    Type[Precisions_random],
]:
    """
    Function to open an element from a file (i.e. `npz` or `pickle` file) in the specified directory path.

    Args:
        file_path: Path to the file
        filetype: Type of the file (i.e. `npz` or `pickle`)

    Returns:
        Element stored in the file
    """

    assert filetype in [
        "pickle",
        "npz",
        "csv.gz",
        "json",
    ], "filetype must be either 'pickle' or 'npz'"
    if filetype == "pickle":
        with open(file_path, "rb") as fl:
            element = pickle.load(fl)
    elif filetype == "npz":
        try:
            element = np.load(file_path)["element"]
        except:
            element = np.load(file_path, allow_pickle=True)["element"]
    elif filetype == "csv.gz":
        element = pd.read_csv(file_path)
    elif filetype == "json":
        with open(file_path, "r") as fl:
            element = json.load(fl)
    else:
        raise ValueError("Filetype not recognized")

    return element


def fix_fs_file(dataset, model, interpretation, scenario):
    path = os.path.join(
        os.getcwd(),
        dataset.name,
        "experiments",
        "feature_selection",
        model,
        interpretation,
        f"scenario_{str(scenario)}",
    )
    file_path = get_most_recent_file(path)
    precs = open_element(file_path)[0]
    aucfs = sum(precs.inverse.mean(axis=1) - precs.direct.mean(axis=1))
    new_precs = NewPrecisions(
        direct=precs.direct,
        inverse=precs.inverse,
        dataset=precs.dataset,
        model=precs.model,
        value=precs.value,
        aucfs=aucfs,
    )
    save_element(new_precs, path, filetype="pickle")


def save_fs_prec(precs: namedtuple, path: str) -> None:
    """
    Function to save the feature selection precisions in a file (i.e. `pickle` file) in the specified directory path.

    Args:
        precs: Feature selection precisions
        path: Directory path where the file will be saved

    Returns:
        The method saves the feature selection precisions and does not return any value

    """

    # aucfs=sum(precs.inverse.mean(axis=1)-precs.direct.mean(axis=1))
    aucfs = np.nansum(
        np.nanmean(precs.inverse, axis=1) - np.nanmean(precs.direct, axis=1)
    )
    new_precs = NewPrecisions(
        direct=precs.direct,
        inverse=precs.inverse,
        dataset=precs.dataset,
        model_name=precs.model_name,
        value=precs.value,
        aucfs=aucfs,
    )
    save_element(new_precs, path, filetype="pickle")


def save_fs_prec_random(precs: namedtuple, path: str) -> None:
    """
    Function to save the feature selection precisions for random features in a file (i.e. `pickle` file) in the specified directory path.

    Args:
        precs: Feature selection precisions for random features
        path: Directory path where the file will be saved

    Returns:
        The method saves the feature selection precisions for random features and does not return any value
    """

    new_precs = Precisions_random(
        random=precs.random, dataset=precs.dataset, model_name=precs.model_name
    )
    save_element(new_precs, path, filetype="pickle")


def get_fs_file(dataset, model, interpretation, scenario):
    path = os.path.join(
        os.getcwd(),
        dataset.name,
        "experiments",
        "feature_selection",
        model,
        interpretation,
        f"scenario_{str(scenario)}",
    )
    file_path = get_most_recent_file(path)
    precs = open_element(file_path)
    return precs


def select_scenario() -> int:
    """
    Function to select the scenario for the experiment (i.e. Scenario 1 or Scenario 2) asking the user to input the scenario number.

    This method was specifically designed to construct the `tutorial.ipynb` notebook for the documentation.

    Returns:
        The selected scenario number (i.e. 1 for Scenario 1 and 2 for Scenario 2)
    """

    scenario = int(input("Press 1 for scenario 1 and 2 for scenario 2: "))
    assert scenario in [1, 2], "Scenario not recognized: Accepted values: [1,2]"
    return scenario


def select_pre_process() -> bool:
    """
    Function to select the pre-processing of the dataset asking the user to input the pre-processing number.

    This method was specifically designed to construct the `tutorial.ipynb` notebook for the documentation.

    Returns:
        Boolean value to indicate whether the dataset should be pre-processed or not
        (i.e. 1 to pre-process the dataset and 2 otherwise)
    """
    pre_process = int(input("Press 1 to pre process the dataset, 2 otherwise: "))
    assert pre_process in [1, 2], "Input values not recognized: Accepted values: [1,2]"
    return pre_process == 1


def select_pre_process_scenario(dataset: Type[Dataset]) -> int:
    """
    Combine the selection of the pre-processing of the dataset and the scenario for the experiment.

    Args:
        dataset: Dataset to be used in the experiment

    Returns:
        The selected scenario number (i.e. 1 for Scenario 1 and 2 for Scenario 2)
    """
    pre_process = select_pre_process()
    scenario = select_scenario()

    if scenario == 2:
        dataset.split_dataset(train_size=1 - dataset.perc_outliers, contamination=0)

    if pre_process == 1:
        dataset.pre_process()
        print("Dataset pre processed\n")
    elif scenario == 2 and not pre_process == 2:
        print("Dataset not preprocessed\n")
        dataset.initialize_test()
    elif scenario == 1 and not pre_process == 2:
        print("Dataset not preprocessed\n")
        dataset.initialize_train_test()

    print(f"Scenario: {scenario}\n")

    print(f"X_train shape: {dataset.X_train.shape}")
    print(f"X_test shape: {dataset.X_test.shape}")

    return scenario


def initialize_perf_dict(basepath: str) -> tuple[dict, dict, str, str]:
    """
    This function initialized the performance dictionaries and creates them as
    empty dictionaries in case they are not initalized, otherwise it loads them.

    Args:
        basepath (str): starting path to define the path to the performance dictionaries

    Returns:
        dict_time, dict_imp_time, dict_time_path, dict_time_imp_path: The two loaded dictionaries and their paths
    """

    perf_dict_dirpath = generate_path(basepath=basepath, folders=["perf_dicts"])

    dict_time_path = os.path.join(perf_dict_dirpath, "dict_time.pickle")
    dict_time_imp_path = os.path.join(perf_dict_dirpath, "dict_time_imp.pickle")

    if not os.path.exists(dict_time_path):
        print("-" * 50)
        print("Creating new fit-predict time dictionary")
        print("-" * 50)

        dict_time = {
            "fit": {
                "EIF+": {},
                "EIF": {},
                "IF": {},
            },
            "predict": {
                "EIF+": {},
                "EIF": {},
                "IF": {},
            },
            "predict_sample": {
                "EIF+": {},
                "EIF": {},
                "IF": {},
            },
        }

        with open(dict_time_path, "wb") as file:
            pickle.dump(dict_time, file)

    with open(dict_time_path, "rb") as file:
        dict_time = pickle.load(file)

    if not os.path.exists(dict_time_imp_path):
        print("-" * 50)
        print("Creating new importances time dictionary")
        print("-" * 50)

        dict_time_imp = {
            "importances": {
                "EIF+_ACME": {},
                "EIF+_KernelSHAP": {},
                "EIF_EXIFFI": {},
                "EIF+_EXIFFI+": {},
                "IF_DIFFI": {},
                "IF_ACME": {},
                "IF_KernelSHAP": {},
            },
        }
        with open(dict_time_imp_path, "wb") as file:
            pickle.dump(dict_time_imp, file)

    with open(dict_time_imp_path, "rb") as file:
        dict_time_imp = pickle.load(file)

    return dict_time, dict_time_imp, dict_time_path, dict_time_imp_path
